Repository wecode-bootcamp-korea/24-2nd-TomorrowsNotebook-backend, pull requests merged in 2021-09, with the labels that each got.

#1 [신우주, 이무현, 박지원] models.py작성
  .gitignore
  books/__init__.py
  books/admin.py
  books/apps.py
  books/migrations/__init__.py
  books/models.py
  books/tests.py
  books/views.py
  core/__init__.py
  core/admin.py
  core/apps.py
  core/migrations/__init__.py
  core/models.py
  core/tests.py
  core/views.py
  libraries/__init__.py
  libraries/admin.py
  libraries/apps.py
  libraries/migrations/__init__.py
  libraries/models.py
  libraries/tests.py
  libraries/views.py
  requirements.txt
  tnb/settings.py
  users/__init__.py
  users/admin.py
  users/apps.py
  users/migrations/__init__.py
  users/models.py
  users/tests.py
  users/views.py
Labels: Status: 수정 요청

#2 [신우주, 이무현, 박지원] models.py작성
  books/migrations/0001_initial.py
  books/migrations/0002_initial.py
  books/models.py
  libraries/migrations/0001_initial.py
  libraries/models.py
  tnb/settings.py
  users/migrations/0001_initial.py
  users/models.py
Labels: Status: 리뷰 요청

#3 [신우주] ADD : SocialLoginView 작성
  books/migrations/0001_initial.py
  books/migrations/0002_initial.py
  books/models.py
  libraries/migrations/0001_initial.py
  libraries/models.py
  requirements.txt
  tnb/urls.py
  users/decorators.py
  users/migrations/0001_initial.py
  users/models.py
  users/tests.py
  users/urls.py
  users/views.py
Labels: Status: 리뷰 요청

#4 ADD: detailview v.1
  .gitignore
  books/migrations/0003_alter_bookinfo_contents.py
  books/migrations/0004_alter_bookinfo_contents.py
  books/migrations/0005_alter_book_description.py
  books/models.py
  books/tests.py
  books/urls.py
  books/views.py
  tnb/urls.py
  users/decorators.py
Labels: Status: 리뷰 요청

#7 [박지원] Add : Shelf delete
  books/urls.py
  libraries/urls.py
  libraries/views.py
  tnb/urls.py
Labels: Status: 리뷰 요청

#12 [이무현]ADD: commentlikeview v.1
  books/tests.py
  books/urls.py
  books/views.py
Labels: Status: 리뷰 요청

#8 [박지원]Add : book library user
  libraries/urls.py
  libraries/views.py
Labels: Status: 리뷰 요청

#10 [박지원] Add : Add books and shelflist
  libraries/urls.py
  libraries/views.py
Labels: Status: Rebase 요청

#6 [신우주] ADD : viewer views.py 작성
  .gitignore
  books/models.py
  books/tests.py
  books/urls.py
  libraries/tests.py
  libraries/urls.py
  libraries/views.py
  users/tests.py
  users/views.py
Labels: Status: 리뷰 요청

#5 [박지원]Add : Add libraries funtion
  books/migrations/0003_auto_20210928_0427.py
  libraries/tests.py
  libraries/urls.py
  libraries/views.py
Labels: Status: 리뷰 요청

#11 [박지원]Add : Add Shelfbooks funtion
  libraries/urls.py
  libraries/views.py
Labels: Status: 리뷰 요청

#9 ADD: commentview1
  books/tests.py
  books/urls.py
  books/views.py
Labels: Status: 리뷰 요청

#13 [이무현]ADD: searchmainview v.1
  books/tests.py
  books/views.py
Labels: Status: 리뷰 요청

#14 [이무현]ADD: searchview v.1
  books/tests.py
  books/views.py
Labels: Status: 리뷰 요청

#15 [이무현]ADD: newbooksview
  books/tests.py
  books/urls.py
  books/views.py
Labels: Status: 리뷰 요청

#16 [이무현]ADD: bookrecommendview
  books/tests.py
  books/views.py
Labels: Status: 리뷰 요청

#17 [이무현]ADD: bookpublisherview
  books/tests.py
  books/views.py
Labels: Status: 리뷰 요청

#18 [이무현]ADD: bookgenreview
  books/tests.py
  books/views.py
Labels: Status: Accepted
